---
- summary: |
    Не работает функция "в наличии"
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Снять флажок с иконки "в наличии"
  expected-result: |
    Все товары магазина отображаются на странице
  actual-result: |
    Выводится сообщение "Ничего не найдено!"

- summary: |
    Не работают максимальные и минимальные значения цены при фильтрации товаров
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Выбрать категорию laptops
    3. Ввести цену от 1099 до 1749
  expected-result: |
    Все товары внутри ценовых значений видны на странице 
  actual-result: |
    Товары с минимальным и максимальным значением внутри заданных цен не отображаются 

- summary: |
    Не работает учет скидок при выводе товаров внутри заданных ценовых значений
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Выбрать категрию skincare
    3. Ввести цену 35 в онко ввода "до"
  expected-result: |
    Видны все товары внутри заданных значений и с учетом скидок
  actual-result: |
    Скидки не учитываются при выводе товаров

- summary: |
    Не работает отображение сайта на русском языке
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Изменить язык с английского на русский
  expected-result: |
    Язык функционала и контента сайта сменился с английского на русский
  actual-result: |
    Язык контента не изменился

- summary: |
    Товары дублируются при пролистывании каталога товаров с последней на предыдущую
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Открыть последнюю страницу магазина
    3. Нажать "Previous"
  expected-result: |
    Должна отобразиться следующая страница с другими товарами 
  actual-result: |
    Вместе с новыми товарами отображаются товары с предыдущей страницы 
