---
- summary: |
    Не работает проверка поиска товара по ключевому слову
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Ввести ключевое слово товара в строку поиска
  expected-result: |
    На странице магазина появятся товары, соответствующие ключевому слову
  actual-result: |
    На странице появляется сообщение "Ничего не найдено!" 

- summary: |
    Не работает проверка фильтрации товаров на странице с другими товарами
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Выбрать страницу со смартфонами
    3. Ввести ключевое слово товара в строку поиска
    4. Выбрать категорию товара "motorcycle"
  expected-result: |
    На странице магазина появятся товары по заданным фильтрам
  actual-result: |
    На странице появляется сообщение "Ничего не найдено!" 

- summary: |
    Не работает адаптивность сайта под мобильные устройства
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Открыть вкладку Devtools
    3. Выбрать iPhone SE
    4. Выбрать iPad Air
    5. Выбрать Sumsung Galaxy A51
  expected-result: |
    Дизайн и функционал сайта не меняются
  actual-result: |
    Нарушена вёрстка, нет адаптивного макета под разные мобильные устройства

- summary: |
    Не работает функция "в наличии"
  environment: |
    Google Chrome   107.0.5304.121 (Официальная сборка) (64 бит)
    ОС Windows 10 24.02
  steps-to-reproduce: |
    1. Зайти на страницу магазина https://hexlet-products-store.vercel.app
    2. Снять флажок с иконки "в наличии"
  expected-result: |
    Все товары магазина отображаются на странице
  actual-result: |
    Выводится сообщение "Ничего не найдено!"
