---
- summary: |
    Проверка поиска товара по ключевому слову
  requirement: |
    При верном вводе ключевого слова в строку поиска пользователь должен увидеть данные товары
  prerequisites: |
    Открыта страница магазина
  test-data: |
    table
    dress
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть данные товары

- summary: |
    Проверка поиска несуществующего товара по ключевому слову
  requirement: |
    При вводе ключевого слова несуществующего товара в строку поиска пользователь должен увидеть сообщение "Ничего не найдено!"
  prerequisites:
    Открыта страница магазина
  test-data: |
    cat
    pencil
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть сообщение "Ничего не найдено!"

- summary: |
    Проверка поиска товара по неверно введённому ключевому слову
  requirement: |
    При неверном вводе ключевого слова товара в строку поиска пользователь должен увидеть сообщение "Ничего не найдено!"
  prerequisites:
    Открыта страница магазина
  test-data: |
    tabel
    drass
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть сообщение "Ничего не найдено!"

- summary: |
    Проверка поиска товара по категории
  requirement: |
    При выборе категории пользователь должен увидеть все товары данной категории
  prerequisites: |
    Открыта страница магазина
  test-data: |
    furniture
    tops
  steps:
    - Выбираем "категории"
    - Выбираем категорию товара из списка
  expected-result: |
    Пользователь должен увидеть все товары данной категории

- summary: |
    Проверка фильтрации товаров
  requirement: |
    При заданных фильтрах пользователь должен увидеть все товары соответствующие фильтрам
  prerequisites:
    Открыта страница магазина
  test-data: |
    motor
    motorcycle
    METRO 70cc Motorcycle
    MR70 BRAVE BULL
  steps:
    - Вводим ключевое слово товара
    - Выбираем категорию "motorcycle"
    - Выбираем производителей "METRO 70cc Motorcycle" и "MR70 BRAVE BULL"
    - Выбираем цену "от 1 до 5000"
  expected-result: |
    Пользователь должен увидеть все товары по заданным фильтрам

- summary: |
    Проверка фильтрации товаров
  requirement: |
    При заданных фильтрах пользователь должен увидеть все товары соответствующие фильтрам
  prerequisites:
    Открыта страница магазина
  test-data: |
    motor
    motorcycle
  steps:
    - Вводим ключевое слово товара
    - Выбираем категорию "motorcycle"
  expected-result: |
    Пользователь должен увидеть все товары по заданным фильтрам

- summary: |
    Проверка фильтрации товаров
  requirement: |
    При заданных фильтрах пользователь должен увидеть все товары соответствующие фильтрам
  prerequisites:
    Открыта страница магазина
  test-data: |
    motorcycle
    METRO 70cc Motorcycle
    MR70 BRAVE BULL
  steps:
    - Выбираем категорию "motorcycle"
    - Выбираем производителей "METRO 70cc Motorcycle" и "MR70 BRAVE BULL"
  expected-result: |
    Пользователь должен увидеть все товары по заданным фильтрам

- summary: |
    Проверка перехода на страницу товара
  requirement: |
    При переходе на страницу товара пользователь должен увидеть выбранный товар и информацию о нём (фото товара, название, рейтинг, цена, количество, описание)
  prerequisites:
    Открыта страница магазина
  test-data: |
    Kabir Singh Square Sunglass
    NIGHT SUIT
  steps:
    - Выбираем любой товар
    - Открывается страница товара с подробной информацией о нём
  expected-result: |
    Пользователь должен увидеть выбранный товар и информацию о нём (фото товара, название, рейтинг, цена, количество, описание)

- summary: |
    Проверка добавления товаров в корзину
  requirement: |
    При нажатии на кнопку "в корзину" любого товара, товар появляется в корзине
  prerequisites:
    Открыта страница магазина
  test-data: |
    кнопка "в корзину"
    кнопка "корзина"
  steps:
    - нажимаем на кнопку "в корзину"
    - переходим во вкладку "корзина"
  expected-result: |
    Пользователь должен увидеть товар в корзине

- summary: |
    Проверка добавления товаров в корзину
  requirement: |
    При нажатии на кнопку "в корзину" любого товара, товар появляется в корзине
  prerequisites:
    Открыта страница магазина
  test-data: |
    кнопка "в корзину"
    кнопка "корзина"
    Sofa for Coffe Cafe
    Sneaker shoes
  steps:
    - выбираем товар
    - нажимаем "в корзину"
    - переходим во вкладку "корзина"
  expected-result: |
    Пользователь должен увидеть товар в корзине

- summary: |
    Проверка просмотра содержимого корзины
  requirement: |
    При переходе в корзину, видны все добавленные раннее товары
  prerequisites:
    Открыта страница магазина
  test-data: |
    кнопка "в корзину"
    кнопка "корзина"
    Sofa for Coffe Cafe
    Sneaker shoes
  steps:
    - выбираем товар "Sofa for Coffe Cafe"
    - нажимаем "в корзину"
    - выбираем товар "Sneaker shoes"
    - нажимаем "в корзину"
    - переходим во вкладку "корзина"
  expected-result: |
    Пользователь должен увидеть все добаленные раннее товары в корзине
