---
- summary: |
    Проверка поиска товара по ключевому слову
  requirement: |
    При верном вводе ключевого слова в строку поиска пользователь должен увидеть данные товары
  prerequisites: |
    Открыта страница магазина
  test-data: |
    furniture
    womens-dresses
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть данные товары

- summary: |
    Проверка поиска несуществующего товара по ключевому слову
  requirement: |
    При вводе ключевого слова несуществующего товара в строку поиска пользователь должен увидеть сообщение "Ничего не найдено!"
  prerequisites:
    Открыта страница магазина
  test-data: |
    cat
    pencil
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть сообщение "Ничего не найдено!"

- summary: |
    Проверка поиска товара по категории
  requirement: |
    При выборе категории пользователь должен увидеть все товары данной категории
  prerequisites: |
    Открыта страница магазина
  test-data: |
    furniture
    tops
  steps:
    - Выбираем "категории"
    - Выбираем категорию товара из списка
  expected-result: |
    Пользователь должен увидеть все товары данной категории

- summary: |
    Проверка фильтрации товаров
  requirement: |
    При заданных фильтрах пользователь должен увидеть все товары соответствующие фильтрам
  prerequisites:
    Открыта страница магазина с мотоциклами
  test-data: |
    motor
    motorcycle
    METRO 70cc Motorcycle
    MR70 BRAVE BULL
  steps:
    - Вводим ключевое слово товара
    - Выбираем категорию "motorcycle"
    - Выбираем производителей "METRO 70cc Motorcycle" и "MR70 BRAVE BULL"
    - Выбираем цену "от 1 до 5000"
  expected-result: |
    Пользователь должен увидеть все товары по заданным фильтрам

- summary: |
    Проверка перехода на страницу товара
  requirement: |
    При переходе на страницу товара пользователь должен увидеть выбранный товар и информацию о нём (фото товара, название, рейтинг, цена, количество, описание)
  prerequisites:
    Открыта страница магазина
  test-data: |
    Kabir Singh Square Sunglass
    NIGHT SUIT
  steps:
    - Выбираем любой товар
    - Открывается страница товара с подробной информацией о нём
  expected-result: |
    Пользователь должен увидеть выбранный товар и информацию о нём (фото товара, название, рейтинг, цена, количество, описание)

- summary: |
    Проверка добавления товаров в корзину
  requirement: |
    При нажатии на кнопку "в корзину" любого товара, товар появляется в корзине
  prerequisites:
    Открыта страница магазина
  test-data: |
  steps:
    - нажимаем на кнопку "в корзину"
    - переходим во вкладку "корзина"
  expected-result: |
    Пользователь должен увидеть товар в корзине

- summary: |
    Проверка добавления товаров в корзину со страницы товара
  requirement: |
    При нажатии на кнопку "в корзину" любого товара, товар появляется в корзине
  prerequisites:
    Открыта страница магазина
  test-data: |
    Sofa for Coffe Cafe
    Sneaker shoes
  steps:
    - выбираем товар
    - нажимаем "в корзину"
    - переходим во вкладку "корзина"
  expected-result: |
    Пользователь должен увидеть товар в корзине

- summary: |
    Проверка мобильной версии сайта
  requirement: |
    Основной контент должен дублироваться на всех устройствах
  prerequisites: |
    Открыта страница магазина, открыта вкладка Devtools
  test-data: |
    iPhone SE
    iPad Air
    Sumsung Galaxy A51
  steps:
    - Открываем Devtools
    - Открываем Toggle Device Toolbar
    - Выбираем iPhone SE
    - Выбираем iPad Air
    - Выбираем Sumsung Galaxy A51
  expected-result: |
    Основной контент дублируется на всех устройствах

- summary: |
    Проверка адаптивности сайта на разных устройствах
  requirement: |
    Дизайн и функционал сайта не должен меняться
  prerequisites: |
    Открыта страница магазина, открыта вкладка Devtools
  test-data: |
    iPhone SE
    iPad Air
    Sumsung Galaxy A51
  steps:
    - Открываем Devtools
    - Открываем Toggle Device Toolbar
    - Выбираем iPhone SE
    - Выбираем iPad Air
    - Выбираем Sumsung Galaxy A51
  expected-result: |
    Дизайн и функционал сайта не меняется

- summary: |
    Проверка оптимизации скорости загрузки
  requirement: |
    Приразных скоростях соединения с Интернетом, основная информация сайта должна прогружаться не дольше 3 секунд
  prerequisites: |
    Открыта страница магазина, открыта вкладка Devtools
  test-data: |
    Fast 3G
    Slow 3G
    No throtting
  steps:
    - Открываем Devtools
    - Выбираем No throtting
    - Обновляем страницу
    - Выбираем Fast 3G
    - Обновляем страницу
    - Выбираем Slow 3G
    - Обновляем страницу
  expected-result: |
    Основной контент сайта прогружается не дольше 3 секунд

- summary: |
    Проверка совместимости с последней версией браузера Opera
  requirement: |
    Сайт должен отображаться и работать в браузере Opera
  prerequisites: |
    Открыт браузер Opera, Открыта страница магазина
  test-data: |
    No data
  steps:
    - Открываем Opera
    - Открываем сайт 
  expected-result: |
    Сайт отображается и работает в браузере Opera

- summary: |
    Проверка совместимости с последней версией браузера Chrome
  requirement: |
    Сайт должен отображаться и работать в браузере Chrome
  prerequisites: |
    Открыт браузер Chrome, Открыта страница магазина
  test-data: |
    No data
  steps:
    - Открываем Chrome
    - Открываем сайт 
  expected-result: |
    Сайт отображается и работает в браузере Chrome

- summary: |
    Проверка совместимости с последней версией браузера Firefox
  requirement: |
    Сайт должен отображаться и работать в браузере Firefox
  prerequisites: |
    Открыт браузер Firefox, Открыта страница магазина
  test-data: |
    No data
  steps:
    - Открываем Firefox
    - Открываем сайт 
  expected-result: |
    Сайт отображается и работает в браузере Firefox

- summary: |
    Проверка совместимости с последней версией браузера Safari
  requirement: |
    Сайт должен отображаться и работать в браузере Safari
  prerequisites: |
    Открыт браузер Safari, Открыта страница магазина
  test-data: |
    No data
  steps:
    - Открываем Safari
    - Открываем сайт 
  expected-result: |
    Сайт отображается и работает в браузере Safari

- summary: |
    Проверка функции "в наличии"
  requirement: |
    При снятии флажка мы должны увидеть все товары магазина
  prerequisites: |
    Открыта страница магазина
  test-data: |
  steps:
    - Снимаем флажок с поля "в наличии"
  expected-result: |
    Пользователь должен увидеть товары магазина

- summary: |
    Проверка граничных значений при вводе цены товаров
  requirement: |
    При верном вводе граничных значений пользователь видит все товары внутри данных значений
  prerequisites: |
    Открыта страница магазина
    Выбрана категория laptops
  test-data: |
    1099
  steps:
    - Вводим значения 1099 - 1749
  expected-result: |
    Пользователь должен увидеть все товары цена которых внутри данных значений

- summary: |
    Проверка учёта скидок при вводе ценовых значений
  requirement: |
    При вводе ценовых значений с учётом скидок пользователь видит все товары по заданным значениям
  prerequisites: |
    Открыта страница магазина
    Выбрана категория skincare
  test-data: |
    - 35
  steps:
    - Вводим в окно ввода "до" значение 35
  expected-result: |
    Пользователь должен увидеть все товары по заданным значениям и с учетом скидок

- summary: |
    Проверка переключения языка на сайте
  requirement: |
    При переключении языка на сайте язык основного функционала меняется
  prerequisites: |
    Открыта страница магазина
  test-data: |
  steps:
    - Переключаем язык с английского на русский
  expected-result: |
    Язык страницы магазина меняется на русский

- summary: |
    Проверка удаления товаров из корзины
  requirement: |
    При нажатии на кнопку удалить товар удаляется из корзины
  prerequisites: |
    Открыта страница магазина
    Открыта корзина с товарами
  test-data: |
  steps:
    - Нажимаем на кнопку "удалить"
  expected-result: |
    Товар исчезает из корзины

- summary: |
    Проверка функции "очистить корзину"
  requirement: |
    При нажати на кнопку "очистить корзину" все товары удаляются из корзины
  prerequisites: |
    Открыта страница магазина
    Выбрана корзина с товарами
  test-data: |
  steps:
    - Нажимаем на кнопку "Очистить корзину"
  expected-result: |
    Все товары исчезают из корзины

- summary: |
    Проверка оформления заказа
  requirement: |
    При оформлении заказаза выводится окно с товарами, их количеством и ценой, общей суммой и сообщение "заказ успешно оформлен"
  prerequisites: |
    Открыта страница магазина
    Открыта корзина с товарами
  test-data: |
  steps:
    - Нажимаем "Оформить заказ"
  expected-result: |
    Пользователь может успешно оформить заказ 
