---
- summary: |
    Проверка поиска товара по ключевому слову
  status: fail

- summary: |
    Проверка поиска несуществующего товара по ключевому слову
  status: pass

- summary: |
    Проверка поиска товара по неверно введённому ключевому слову
  status: pass

- summary: |
    Проверка поиска товара по категории
  status: pass

- summary: |
    Проверка фильтрации товаров
  status: pass

- summary: |
    Проверка перехода на страницу товара
  status: pass

- summary: |
    Проверка добавления товаров в корзину
  status: pass

- summary: |
    Проверка добавления товаров в корзину со страницы товара
  status: pass

- summary: |
    Проверка просмотра содержимого корзины
  status: pass

- summary: |
    Проверка мобильной версии сайта
  status: fail

- summary: |
    Проверка адаптивности сайта на разных устройствах
  status: pass

- summary: |
    Проверка оптимизации скорости загрузки
  status: pass

- summary: |
    Проверка совместимости с последней версией браузера Opera
  status: pass

- summary: |
    Проверка совместимости с последней версией браузера Chrome
  status: pass

- summary: |
    Проверка совместимости с последней версией браузера Firefox
  status: pass

- summary: |
    Проверка функции "в наличии"
  status: fail

- summary: |
    Проверка совместимости с последней версией браузера Safari
  status: pass  

- summary: |
    Проверка сброса категории
  status: fail

- summary: |
    Проверка ввода количества товаров
  status: fail

- summary: |
    Проверка граничных значений при вводе цены товаров
  status: fail

- summary: |
    Проверка учёта скидок при вводе ценовых значений
  status: fail 
