---
- summary: |
    Проверка поиска товара по ключевому слову
  status: fail

- summary: |
    Проверка поиска несуществующего товара по ключевому слову
  status: pass

- summary: |
    Проверка поиска товара по категории
  status: pass

- summary: |
    Проверка фильтрации товаров
  status: pass

- summary: |
    Проверка перехода на страницу товара
  status: pass

- summary: |
    Проверка добавления товаров в корзину
  status: pass

- summary: |
    Проверка добавления товаров в корзину со страницы товара
  status: pass

- summary: |
    Проверка функции "в наличии"
  status: fail

- summary: |
    Проверка граничных значений при вводе цены товаров
  status: fail

- summary: |
    Проверка учёта скидок при вводе ценовых значений
  status: fail 

- summary: |
    Проверка переключения языка на сайте
  status: pass

- summary: |
    Проверка удаления товаров из корзины
  status: pass

- summary: |
    Проверка функции очистить корзину
  status: pass

- summary: |
    Проверка оформления заказа
  status: pass 
