---
- summary: |
    Проверка поиска товара по ключевому слову
  requirement: |
    При верном вводе ключевого слова в строку поиска пользователь должен увидеть данные товары
  prerequisites: |
    Открыта страница магазина
  test-data: |
    table
    dress
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть данные товары

- summary: |
    Проверка поиска несуществующего товара по ключевому слову
  requirement: |
    При вводе ключевого слова несуществующего товара в строку поиска пользователь должен увидеть сообщение "Ничего не найдено!"
  prerequisites:
    Открыта страница магазина
  test-data: |
    cat
    pencil
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть сообщение "Ничего не найдено!"

- summary: |
    Проверка поиска товара по неверно введённому ключевому слову
  requirement: |
    При неверном вводе ключевого слова товара в строку поиска пользователь должен увидеть сообщение "Ничего не найдено!"
  prerequisites:
    Открыта страница магазина
  test-data: |
    tabel
    drass
  steps:
    - Вводим ключевое слово товара
  expected-result: |
    Пользователь должен увидеть сообщение "Ничего не найдено!"

- summary: |
    Проверка поиска товара по категории
  requirement: |
    При выборе категории пользователь должен увидеть все товары данной категории
  prerequisites: |
    Открыта страница магазина
  test-data: |
    furniture
    tops
  steps:
    - Выбираем "категории"
    - Выбираем категорию товара из списка
  expected-result: |
    Пользователь должен увидеть все товары данной категории

- summary: |
    Проверка фильтрации товаров
  requirement: |
    При заданных фильтрах пользователь должен увидеть все товары соответствующие фильтрам
  prerequisites:
    Открыта страница магазина
  test-data: |
    motor
    motorcycle
    METRO 70cc Motorcycle
    MR70 BRAVE BULL
  steps:
    - Вводим ключевое слово товара
    - Выбираем категорию "motorcycle"
    - Выбираем производителей "METRO 70cc Motorcycle" и "MR70 BRAVE BULL"
  expected-result: |
    Пользователь должен увидеть все товары по заданным фильтрам
